services:
  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/app
    ports:
      - "8000:8000"
    environment:
      - WATCHFILE_FORCE_POLLING=true

  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "33306:3306"

  frontend:
    build:
      context: ./frontend/my-app
    volumes:
      - ./frontend/my-app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  db-data:
  node_modules:
