services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - WATCHFILE_FORCE_POLLING=true
    
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33306:3306"

  # 新しいフロントエンドサービス
  frontend:
    build: 
      context: ./frontend/my-app
      dockerfile: dockerfile
    volumes:
      - ./frontend/my-app:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    depends_on:
      - demo-app

volumes:
  db-data:
