version: '3.9'

services:
  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/app
    ports:
      - "8000:8000"
    environment:
      - WATCHFILE_FORCE_POLLING=true

  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "33306:3306"

  frontend:
    build:
      context: ./frontend/my-vite-app
      dockerfile: Dockerfile
    volumes:
      - ./frontend/my-vite-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"  # Viteのデフォルトポート
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  db-data:

